name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: flying-ufo/action-upload-artifacts-and-release@main
        with:
          path: |
            x.txt
            y.txt
          
