name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Upload artifact and release
        uses: flying-ufo/action-upload-artifacts-and-release@main
        with:
          path: |
            x.txt
            y.txt
          create-release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
