# Change

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifact and release
        uses: ptc-lfruehstueck/action-upload-artifacts-and-release-assets@feature/upload2.0 
        with:
          path: |
            x.txt
            y.txt
          upload-release-files: false
          release-upload-url: ${{ steps.get_release.outputs.upload_url }}
