# Changed!!!!

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifact and release
        uses: nanoufo/action-upload-artifacts-and-release-assets@fix/node-version-20
        with:
          path: |
            x.txt
            y.txt
          upload-release-files: true
          release-upload-url: ${{ steps.get_release.outputs.upload_url }}
